version: "3.9"
services:
  calicot.api:
    build:
      context: .
      dockerfile: ./Calicot.API/Dockerfile
    ports:
      - 8090:443
  calicot.webapp:
    build:
      context: .
      dockerfile: ./Calicot.WebApp/Dockerfile
    ports:
      - 8091:80
      - 8092:443
    depends_on:
      - calicot.api
    
   